-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.activities
(
    id uuid NOT NULL,
    type enum_activities_type NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "user" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    details text COLLATE pg_catalog."default",
    "ipAddress" character varying(255) COLLATE pg_catalog."default",
    "timestamp" timestamp with time zone,
    CONSTRAINT activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.appointments
(
    id uuid NOT NULL,
    "appointmentDate" timestamp with time zone NOT NULL,
    status enum_appointments_status DEFAULT 'pending'::enum_appointments_status,
    reason text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    "doctorId" uuid NOT NULL,
    "patientId" uuid NOT NULL,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.doctors
(
    id uuid NOT NULL,
    "userId" uuid NOT NULL,
    specialization character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'General'::character varying,
    "licenseNumber" character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'LIC-x589kikfh'::character varying,
    "yearsOfExperience" integer DEFAULT 0,
    "availableSlots" integer DEFAULT 0,
    bio text COLLATE pg_catalog."default",
    "imageUrl" character varying(255) COLLATE pg_catalog."default",
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT doctors_pkey PRIMARY KEY (id),
    CONSTRAINT "doctors_licenseNumber_key" UNIQUE ("licenseNumber"),
    CONSTRAINT "doctors_userId_key" UNIQUE ("userId")
);

CREATE TABLE IF NOT EXISTS public.lab_tests
(
    id uuid NOT NULL,
    "medicalRecordId" uuid NOT NULL,
    "patientId" uuid NOT NULL,
    "testName" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "testCode" character varying(255) COLLATE pg_catalog."default",
    "orderedDate" timestamp with time zone,
    "resultDate" timestamp with time zone,
    "resultValue" text COLLATE pg_catalog."default",
    "normalRange" character varying(255) COLLATE pg_catalog."default",
    unit character varying(255) COLLATE pg_catalog."default",
    status enum_lab_tests_status DEFAULT 'pending'::enum_lab_tests_status,
    notes text COLLATE pg_catalog."default",
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT lab_tests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.medical_records
(
    id uuid NOT NULL,
    "patientId" uuid NOT NULL,
    "doctorId" uuid,
    "visitDate" timestamp with time zone,
    department character varying(255) COLLATE pg_catalog."default",
    reason text COLLATE pg_catalog."default",
    symptoms text COLLATE pg_catalog."default",
    "clinicalExamination" text COLLATE pg_catalog."default",
    diagnosis text COLLATE pg_catalog."default",
    "primaryDiagnosis" character varying(255) COLLATE pg_catalog."default",
    treatment text COLLATE pg_catalog."default",
    "examResult" text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    status enum_medical_records_status DEFAULT 'draft'::enum_medical_records_status,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT medical_records_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.patients
(
    id uuid NOT NULL,
    "userId" uuid NOT NULL,
    "medicalRecordNumber" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "dateOfBirth" timestamp with time zone,
    gender enum_patients_gender,
    "bloodType" character varying(255) COLLATE pg_catalog."default",
    allergies text COLLATE pg_catalog."default",
    "medicalHistory" text COLLATE pg_catalog."default",
    insurance character varying(255) COLLATE pg_catalog."default",
    "emergencyContact" character varying(255) COLLATE pg_catalog."default",
    "emergencyPhone" character varying(255) COLLATE pg_catalog."default",
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT patients_pkey PRIMARY KEY (id),
    CONSTRAINT "patients_medicalRecordNumber_key" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key1" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key10" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key11" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key12" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key13" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key14" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key15" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key2" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key3" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key4" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key5" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key6" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key7" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key8" UNIQUE ("medicalRecordNumber"),
    CONSTRAINT "patients_medicalRecordNumber_key9" UNIQUE ("medicalRecordNumber")
);

CREATE TABLE IF NOT EXISTS public.prescriptions
(
    id uuid NOT NULL,
    "medicalRecordId" uuid NOT NULL,
    "patientId" uuid NOT NULL,
    "medicationName" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dosage character varying(255) COLLATE pg_catalog."default",
    quantity integer,
    unit character varying(255) COLLATE pg_catalog."default",
    frequency character varying(255) COLLATE pg_catalog."default",
    duration character varying(255) COLLATE pg_catalog."default",
    route character varying(255) COLLATE pg_catalog."default",
    instructions text COLLATE pg_catalog."default",
    "prescribedDate" timestamp with time zone,
    "expiryDate" timestamp with time zone,
    status enum_prescriptions_status DEFAULT 'active'::enum_prescriptions_status,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT prescriptions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.system_logs
(
    id uuid NOT NULL,
    type enum_system_logs_type DEFAULT 'INFO'::enum_system_logs_type,
    "user" character varying(255) COLLATE pg_catalog."default",
    action character varying(255) COLLATE pg_catalog."default" NOT NULL,
    details text COLLATE pg_catalog."default",
    "ipAddress" character varying(255) COLLATE pg_catalog."default",
    "timestamp" timestamp with time zone,
    CONSTRAINT system_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.system_settings
(
    id uuid NOT NULL,
    "appName" character varying(255) COLLATE pg_catalog."default" DEFAULT 'QLBA - Electronic Health Record System'::character varying,
    "appVersion" character varying(255) COLLATE pg_catalog."default" DEFAULT '1.0.0'::character varying,
    "maintenanceMode" boolean DEFAULT false,
    "maxUploadSize" integer DEFAULT 10,
    "sessionTimeout" integer DEFAULT 30,
    "emailNotifications" boolean DEFAULT true,
    "smsNotifications" boolean DEFAULT true,
    "backupEnabled" boolean DEFAULT true,
    "backupFrequency" "enum_system_settings_backupFrequency" DEFAULT 'daily'::"enum_system_settings_backupFrequency",
    theme enum_system_settings_theme DEFAULT 'light'::enum_system_settings_theme,
    language enum_system_settings_language DEFAULT 'vi'::enum_system_settings_language,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_preferences
(
    id serial NOT NULL,
    "userId" uuid NOT NULL,
    theme character varying(255) COLLATE pg_catalog."default" DEFAULT 'light'::character varying,
    language character varying(255) COLLATE pg_catalog."default" DEFAULT 'vi'::character varying,
    notifications boolean DEFAULT true,
    "emailNotifications" boolean DEFAULT true,
    "smsNotifications" boolean DEFAULT true,
    "autoBackup" boolean DEFAULT true,
    "backupFrequency" character varying(255) COLLATE pg_catalog."default" DEFAULT 'daily'::character varying,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
    CONSTRAINT "user_preferences_userId_key" UNIQUE ("userId")
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "firstName" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "lastName" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role enum_users_role DEFAULT 'patient'::enum_users_role,
    phone character varying(255) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    avatar character varying(255) COLLATE pg_catalog."default",
    "isActive" boolean DEFAULT true,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_email_key1 UNIQUE (email),
    CONSTRAINT users_email_key10 UNIQUE (email),
    CONSTRAINT users_email_key11 UNIQUE (email),
    CONSTRAINT users_email_key12 UNIQUE (email),
    CONSTRAINT users_email_key13 UNIQUE (email),
    CONSTRAINT users_email_key14 UNIQUE (email),
    CONSTRAINT users_email_key15 UNIQUE (email),
    CONSTRAINT users_email_key16 UNIQUE (email),
    CONSTRAINT users_email_key2 UNIQUE (email),
    CONSTRAINT users_email_key3 UNIQUE (email),
    CONSTRAINT users_email_key4 UNIQUE (email),
    CONSTRAINT users_email_key5 UNIQUE (email),
    CONSTRAINT users_email_key6 UNIQUE (email),
    CONSTRAINT users_email_key7 UNIQUE (email),
    CONSTRAINT users_email_key8 UNIQUE (email),
    CONSTRAINT users_email_key9 UNIQUE (email)
);

ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT "appointments_doctorId_fkey" FOREIGN KEY ("doctorId")
    REFERENCES public.doctors (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT "appointments_patientId_fkey" FOREIGN KEY ("patientId")
    REFERENCES public.patients (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.doctors
    ADD CONSTRAINT "doctors_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "doctors_userId_key"
    ON public.doctors("userId");


ALTER TABLE IF EXISTS public.lab_tests
    ADD CONSTRAINT "lab_tests_medicalRecordId_fkey" FOREIGN KEY ("medicalRecordId")
    REFERENCES public.medical_records (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lab_tests
    ADD CONSTRAINT "lab_tests_patientId_fkey" FOREIGN KEY ("patientId")
    REFERENCES public.patients (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.medical_records
    ADD CONSTRAINT "medical_records_doctorId_fkey" FOREIGN KEY ("doctorId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.medical_records
    ADD CONSTRAINT "medical_records_patientId_fkey" FOREIGN KEY ("patientId")
    REFERENCES public.patients (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.patients
    ADD CONSTRAINT "patients_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.prescriptions
    ADD CONSTRAINT "prescriptions_medicalRecordId_fkey" FOREIGN KEY ("medicalRecordId")
    REFERENCES public.medical_records (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.prescriptions
    ADD CONSTRAINT "prescriptions_patientId_fkey" FOREIGN KEY ("patientId")
    REFERENCES public.patients (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_preferences
    ADD CONSTRAINT "user_preferences_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "user_preferences_userId_key"
    ON public.user_preferences("userId");

END;